[book]
authors = ["Alexander Veltman"]
language = "en"
multilingual = false
src = "src"
title = "Programming Lab Manual"
description = "An reference guide for undergraduate physics students wanting some help with their lab assignments."

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/codecalec/ProgrammingLabManual"
additional-css = ["css/centre_images.css"]