[book]
authors = ["Alexander Veltman"]
language = "en"
multilingual = false
src = "src"
title = "Programming Lab Manual"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/codecalec/ProgrammingLabManual"
additional-css = ["src/centre_images.css"]